# Import necessary libraries.
from pathlib import Path

USER_PATH = Path.home()
SCRIPT_PATH = USER_PATH / ("Projeto-01")
SCRIPT_FOLDER_1 = SCRIPT_PATH / ("01-ADMINISTRAÇÃO")
SCRIPT_FOLDER_1_1 = SCRIPT_FOLDER_1 / ("01-FUNCIONARIOS")
SCRIPT_FOLDER_1_2 = SCRIPT_FOLDER_1 / ("02-FORNECEDORES")


SCRIPT_FOLDER_2 = SCRIPT_PATH / ("02-LOGISTICA")
SCRIPT_FOLDER_2_1 = SCRIPT_FOLDER_2 / ("01-AGENDAMENTO")
SCRIPT_FOLDER_2_2 = SCRIPT_FOLDER_2 / ("02-EXPEDIÇÃO")
SCRIPT_FOLDER_2_3 = SCRIPT_FOLDER_2 / ("03-ESTOQUE")

DB_SUPPLIERS = "Suppliers.db"
DB__EMPLOYEES = "Employees.db"

MONTHS = [
    "01-JANEIRO",
    "02-FEVEREIRO",
    "03-MARÇO",
    "04-ABRIL",
    "05-MAIO",
    "06-JUNHO",
    "07-JULHO",
    "08-AGOSTO",
    "09-SETEMBRO",
    "10-OUTUBRO",
    "11-NOVEMBRO",
    "12-DEZEMBRO"
]

